name: diagram converter

on:
  push:
    paths:
      - "./doc/diagrams/*"


jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Convert digramm to png
      uses: Burnett01/actions-drawio@1.2
      with:
        src: ./doc/diagrams/*.xml
        dest: ./doc/img/*.png
