name: diagram converter

on:
  push:


jobs:
  convert:
    runs-on: ubuntu
    steps:
    - uses: actions/checkout@v2
    - name: Convert digramm to png
      uses: Burnett01/actions-drawio@1.2
      with:
        src: ./doc/diagrams/*.xml
        dest: ./doc/img/*.png
