name: Test compilation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  makefile_build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Compile
      run: make
